#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "MKL25Z4.h"
#include "BoardInit.h"
#include "SysTickScheduler.h"
#include "arm_cortex_m_multitasking.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE Freescale FRDM-KL25Z
#define MW_CONNECTIONINFO_SERIAL_BAUDRATE codertarget.freedomboard.internal.uartActionCallback
#define MW_CONNECTIONINFO_SERIAL_COMPORT codertarget.freedomboard.internal.getExternalSerialPortName
#define MW_CONNECTIONINFO_SERIAL_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION Serial
#define MW_EXTMODE_SELECT_UART 0.000000
#define MW_EXTMODE_COMPORT COM27
#define MW_RTOS Baremetal
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_CLOCKING_CPUCLOCKRATEMHZ 48
#define MW_I2C0_SCL_PIN 0
#define MW_I2C0_SDA_PIN 0
#define MW_I2C1_SCL_PIN 0
#define MW_I2C1_SDA_PIN 0
#define MW_TPM0_FREQUENCY 4166
#define MW_TPM1_FREQUENCY 50
#define MW_TPM2_FREQUENCY 4166
#define MW_UART0_BAUDRATE 115200
#define MW_UART0_TX_PINSELECTION 0
#define MW_UART0_RX_PINSELECTION 0
#define MW_UART1_BAUDRATE 115200
#define MW_UART1_TX_PINSELECTION 0
#define MW_UART1_RX_PINSELECTION 0
#define MW_UART2_BAUDRATE 115200
#define MW_UART2_TX_PINSELECTION 0
#define MW_UART2_RX_PINSELECTION 0
#define MW_PIL_SELECT_UART 0.000000
#define MW_PIL_COMPORT COM1
#define MW_DATAVERSION 2016.02

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
